services:
  postgres:
    container_name: logisticPostgres
    image: postgres
    environment:
      POSTGRES_USER: logisticcompany
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logisticdb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_logistic
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
