server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: price
          uri: lb://PRICE
          predicates:
            - Path=/api/v1/price/**
        - id: info
          uri: lb://INFO
          predicates:
            - Path=/api/v1/info/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true