server:
  port: 8080
spring:
  application:
    name: logisticservice

  datasource:
    username: logisticcompany
    url: jdbc:postgresql://localhost:5432/logisticdb
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
