server:
  port: 8082

spring:
  application:
    name: info

  datasource:
    username: logisticcompany
    url: jdbc:postgresql://localhost:5432/logisticdb
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka